[project]
name = "fake-dialup"
version = "0.1.0"
description = "I'm not even sure anymore."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "brotli>=1.1.0",
    "click>=8.1.8",
    "numpy>=2.2.1",
    "pyaudio>=0.2.14",
]
